version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: /Dockerfile
      target: development
    command: npm run start:dev
    env_file:
      - /.env
    ports:
      - '4000:4000'
    volumes:
      - .:/user/src/app
